sudo: required
services:
  - docker

before_install:
  - docker build -t hankchanocd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hankchanocd/react-test npm test -- --coverage

after_success:
  - docker build -t hankchanocd/multi-client ./client
  - docker build -t hankchanocd/multi-nginx ./nginx
  - docker build -t hankchanocd/multi-server ./server
  - docker build -t hankchanocd/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images and push them to docker hub
  - docker push hankchanocd/multi-client
  - docker push hankchanocd/multi-nginx
  - docker push hankchanocd/multi-server
  - docker push hankchanocd/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: bucket_name
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
